"""Renders the user manual inside the app.

Anyone testing a deployed instance has a URL and nothing else -- no repository, no
docs folder. The manual is read from ``docs/USER_MANUAL.md`` at run time so there is
exactly one copy of it to maintain.
"""

from __future__ import annotations

import re
from pathlib import Path

import streamlit as st

DOCS = Path(__file__).resolve().parent.parent / "docs"
MANUAL_PATH = DOCS / "USER_MANUAL.md"

#: Pre-built distributable copies, offered when present. Generated by
#: ``python tools/build_manual_docs.py``.
DOWNLOADS = [
    ("Download as PDF", DOCS / "PA_Workbench_User_Manual.pdf", "application/pdf"),
    ("Download as Word", DOCS / "PA_Workbench_User_Manual.docx",
     "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    ("Download as Markdown", MANUAL_PATH, "text/markdown"),
]


def _escape_dollars_outside_code(text: str) -> str:
    """Escape ``$`` so Streamlit does not parse pairs of them as LaTeX math.

    Fenced code blocks are left alone -- a backslash there would render literally.
    """
    parts = re.split(r"(```.*?```)", text, flags=re.S)
    return "".join(
        part if part.startswith("```") else part.replace("$", r"\$")
        for part in parts
    )


def render() -> None:
    st.title("User Manual")

    if not MANUAL_PATH.exists():
        st.error(
            "The manual file is missing. It should be at `docs/USER_MANUAL.md` "
            "relative to the application root."
        )
        return

    raw = MANUAL_PATH.read_text(encoding="utf-8")

    available = [(label, path, mime) for label, path, mime in DOWNLOADS if path.exists()]
    for col, (label, path, mime) in zip(st.columns(len(available)), available):
        col.download_button(
            label,
            data=path.read_bytes(),
            file_name=path.name,
            mime=mime,
            use_container_width=True,
        )
    st.caption(
        "The PDF and Word copies are generated from this same text, so all three stay "
        "in step. Print or hand out whichever suits."
    )
    st.divider()

    # Drop the document's own H1 -- st.title already supplies one.
    body = re.sub(r"^# .*?\n", "", raw, count=1)
    st.markdown(_escape_dollars_outside_code(body))
